// GRUDA Wars character roster — frame counts verified from actual sprite file dimensions
// All sprites at /fighter2d/characters/<folder>/<file>.png

export interface GrudaCharDef {
  id: string;
  name: string;
  folder: string;
  color: string;
  frameSize: number; // px per frame (height of sprite strip)
  idle: [string, number];
  walk: [string, number];
  attack: [string, number];
  hurt: [string, number];
  death: [string, number];
  attack2?: [string, number];
  block?: [string, number];
  jump?: [string, number];
  cast?: [string, number];
  special?: [string, number];
  roll?: [string, number];
  projectile?: string;
  effectSrc?: string;
  effectFrames?: number;
  atk: number;
  spd: number;
  superDmg: number;
  superName: string;
}

export const GRUDA_ROSTER: GrudaCharDef[] = [
  // ─── ORIGINAL 7 (100x100 frames) ──────────────────────────────
  { id:"knight", name:"Knight", folder:"Knight", color:"#e74c3c", frameSize:100,
    idle:["Knight-Idle.png",6], walk:["Knight-Walk.png",8], attack:["Knight-Attack03.png",11],
    hurt:["Knight-Hurt.png",4], death:["Knight-Death.png",4], block:["Knight-Block.png",4],
    attack2:["Knight-Attack02.png",10],
    effectSrc:"Knight-Attack03_Effect.png", effectFrames:11,
    atk:13, spd:5.6, superDmg:35, superName:"Divine Judgment" },
  { id:"archer", name:"Archer", folder:"Archer", color:"#27ae60", frameSize:100,
    idle:["Archer-Idle.png",6], walk:["Archer-Walk.png",8], attack:["Archer-Attack02.png",12],
    hurt:["Archer-Hurt.png",4], death:["Archer-Death.png",4], attack2:["Archer-Attack01.png",9],
    effectSrc:"Archer-Attack02_Effect.png", effectFrames:12, projectile:"Arrow.png",
    atk:9, spd:6.8, superDmg:30, superName:"Storm of Arrows" },
  { id:"wizard", name:"Wizard", folder:"Wizard", color:"#8e44ad", frameSize:100,
    idle:["Wizard-Idle.png",6], walk:["Wizard-Walk.png",8], attack:["Wizard-Attack01.png",6],
    hurt:["Wizard-Hurt.png",4], death:["Wizard-DEATH.png",4], attack2:["Wizard-Attack02.png",6],
    effectSrc:"Wizard-Attack01_Effect.png", effectFrames:10, projectile:"Wizard-Projectile.png",
    atk:10, spd:5.4, superDmg:40, superName:"Arcane Apocalypse" },
  { id:"orc", name:"Orc", folder:"Orc", color:"#2ecc71", frameSize:100,
    idle:["Orc-Idle.png",6], walk:["Orc-Walk.png",8], attack:["Orc-Attack01.png",6],
    hurt:["Orc-Hurt.png",4], death:["Orc-Death.png",4], attack2:["Orc-Attack02.png",6],
    effectSrc:"Orc-attack01_Effect.png", effectFrames:6,
    atk:15, spd:5.0, superDmg:38, superName:"Waaagh! Smash" },
  { id:"skeleton", name:"Armored Skeleton", folder:"Armored-Skeleton", color:"#95a5a6", frameSize:100,
    idle:["Armored Skeleton-Idle.png",6], walk:["Armored Skeleton-Walk.png",8],
    attack:["Armored Skeleton-Attack02.png",9], hurt:["Armored Skeleton-Hurt.png",4],
    death:["Armored Skeleton-Death.png",4], attack2:["Armored Skeleton-Attack01.png",8],
    effectSrc:"Armored Skeleton-Attack02_Effect.png", effectFrames:9,
    atk:11, spd:5.8, superDmg:32, superName:"Soul Harvest" },
  { id:"swordsman", name:"Swordsman", folder:"Swordsman", color:"#e67e22", frameSize:100,
    idle:["Swordsman-Idle.png",6], walk:["Swordsman-Walk.png",8], attack:["Swordsman-Attack01.png",7],
    hurt:["Swordsman-Hurt.png",5], death:["Swordsman-Death.png",4], attack2:["Swordsman-Attack02.png",15],
    effectSrc:"Swordsman-Attack01_Effect.png", effectFrames:7,
    atk:12, spd:6.4, superDmg:33, superName:"Thousand Cuts" },
  { id:"priest", name:"Priest", folder:"Priest", color:"#f1c40f", frameSize:100,
    idle:["Priest-Idle.png",6], walk:["Priest-Walk.png",8], attack:["Priest-Attack.png",9],
    hurt:["Priest-Hurt.png",4], death:["Priest-Death.png",4], cast:["Priest-Heal.png",6],
    effectSrc:"Priest-Attack_effect.png", effectFrames:5,
    atk:9, spd:5.2, superDmg:36, superName:"Holy Smite" },

  // ─── 100px frame GRUDA heroes ──────────────────────────────────
  { id:"armored-orc", name:"Armored Orc", folder:"armored-orc", color:"#196f3d", frameSize:100,
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",7],
    hurt:["hurt.png",4], death:["death.png",4], block:["block.png",4],
    attack2:["attack2.png",8], special:["attack3.png",9],
    atk:14, spd:5.0, superDmg:38, superName:"Iron Tusk" },
  { id:"elite-orc", name:"Elite Orc", folder:"elite-orc", color:"#1e8449", frameSize:100,
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",7],
    hurt:["hurt.png",4], death:["death.png",4], attack2:["attack2.png",11], special:["attack3.png",9],
    atk:15, spd:5.2, superDmg:40, superName:"Orc Warlord" },
  { id:"knight-templar", name:"Knight Templar", folder:"knight-templar", color:"#f39c12", frameSize:100,
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack3.png",11],
    hurt:["hurt.png",4], death:["death.png",4], block:["block.png",4],
    attack2:["attack2.png",8], cast:["cast.png",11],
    atk:14, spd:5.4, superDmg:37, superName:"Holy Crusade" },
  { id:"barbarian-ranger", name:"Barbarian Ranger", folder:"barbarian-ranger", color:"#c0392b", frameSize:100,
    idle:["idle.png",6], walk:["walk.png",6], attack:["attack1.png",6],
    hurt:["hurt.png",4], death:["death.png",4], attack2:["attack2.png",9],
    projectile:"axe.png",
    atk:12, spd:5.6, superDmg:34, superName:"Axe Storm" },
  { id:"elf-ranger", name:"Elf Ranger", folder:"elf-ranger", color:"#27ae60", frameSize:100,
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",6],
    hurt:["hurt.png",4], death:["death.png",4], attack2:["attack2.png",6],
    projectile:"arrow_long.png",
    atk:10, spd:7.0, superDmg:28, superName:"Elven Barrage" },
  { id:"werebear", name:"Werebear", folder:"werebear", color:"#6e2c00", frameSize:100,
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",9],
    hurt:["hurt.png",4], death:["death.png",4], attack2:["attack2.png",13], special:["attack3.png",9],
    atk:16, spd:4.6, superDmg:42, superName:"Bear Maul" },
  { id:"werewolf", name:"Werewolf", folder:"werewolf", color:"#4a235a", frameSize:100,
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",9],
    hurt:["hurt.png",4], death:["death.png",4], attack2:["attack2.png",13],
    atk:14, spd:6.8, superDmg:35, superName:"Lunar Frenzy" },
  { id:"barbarian-warrior", name:"Barbarian", folder:"barbarian-warrior", color:"#d35400", frameSize:100,
    idle:["idle.png",28], walk:["walk.png",14], attack:["attack1.png",53],
    hurt:["hurt.png",14], death:["death.png",71], attack2:["attack2.png",53],
    atk:16, spd:4.8, superDmg:42, superName:"Berserker Fury" },

  // ─── 96px frame heroes ─────────────────────────────────────────
  { id:"dark-knight", name:"Dark Knight", folder:"dark-knight", color:"#2c3e50", frameSize:96,
    idle:["idle.png",5], walk:["walk.png",8], attack:["attack1.png",11],
    hurt:["hurt.png",4], death:["death.png",5], jump:["jump.png",8], attack2:["attack2.png",15],
    effectSrc:"slash_arc.png", effectFrames:6,
    atk:14, spd:5.8, superDmg:36, superName:"Shadow Cleave" },
  { id:"shadow-warrior", name:"Shadow Warrior", folder:"shadow-warrior", color:"#1a1a2e", frameSize:96,
    idle:["idle.png",5], walk:["walk.png",8], attack:["attack1.png",16],
    hurt:["hurt.png",4], death:["death.png",5], jump:["jump.png",7], attack2:["attack2.png",9],
    atk:13, spd:6.4, superDmg:34, superName:"Shadow Dance" },
  { id:"pirate-captain", name:"Pirate Captain", folder:"pirate-captain", color:"#784212", frameSize:96,
    idle:["Idle.png",4], walk:["Walk.png",6], attack:["Attack1.png",6],
    hurt:["Hurt.png",2], death:["Death.png",6], special:["Special.png",6], attack2:["Attack2.png",6],
    projectile:"bullet.png",
    atk:13, spd:5.8, superDmg:35, superName:"Cannon Barrage" },
  { id:"crossbowman", name:"Crossbowman", folder:"crossbowman", color:"#566573", frameSize:96,
    idle:["Idle.png",6], walk:["Walk.png",8], attack:["Attack_1.png",4],
    hurt:["Hurt.png",3], death:["Dead.png",4], jump:["Jump.png",10], attack2:["Attack_2.png",4],
    projectile:"ballista_bolt.png",
    atk:12, spd:5.8, superDmg:32, superName:"Bolt Barrage" },

  // ─── 128px frame heroes ────────────────────────────────────────
  { id:"fire-knight", name:"Fire Knight", folder:"fire-knight", color:"#e74c3c", frameSize:128,
    idle:["idle.png",18], walk:["run.png",18], attack:["attack1.png",25],
    hurt:["hurt.png",14], death:["death.png",29], block:["block.png",22],
    jump:["jump.png",45], attack2:["attack2.png",43], special:["special.png",40], roll:["roll.png",18],
    atk:14, spd:6.2, superDmg:38, superName:"Inferno Blade" },
  { id:"fire-wizard", name:"Fire Wizard", folder:"fire-wizard", color:"#e74c3c", frameSize:128,
    idle:["idle.png",7], walk:["walk.png",6], attack:["attack1.png",4],
    hurt:["hurt.png",3], death:["death.png",6], jump:["jump.png",9],
    attack2:["attack2.png",4], cast:["fireball.png",8],
    projectile:"fireball.png",
    atk:10, spd:5.4, superDmg:42, superName:"Meteor Rain" },
  { id:"lightning-mage", name:"Lightning Mage", folder:"lightning-mage", color:"#3498db", frameSize:128,
    idle:["idle.png",7], walk:["walk.png",7], attack:["attack1.png",10],
    hurt:["hurt.png",3], death:["death.png",5], jump:["jump.png",8],
    attack2:["attack2.png",4], cast:["light_ball.png",7],
    effectSrc:"lightning-bolt.png", effectFrames:6,
    atk:11, spd:5.6, superDmg:40, superName:"Thunder God" },
  { id:"gunslinger", name:"Gunslinger", folder:"gunslinger", color:"#7f8c8d", frameSize:128,
    idle:["idle.png",4], walk:["walk.png",6], attack:["attack.png",6],
    hurt:["hurt.png",2], death:["death.png",6],
    projectile:"bullet.png",
    atk:11, spd:6.6, superDmg:30, superName:"Dead Eye" },
  { id:"necromancer", name:"Necromancer", folder:"necromancer", color:"#6c3483", frameSize:128,
    idle:["idle.png",10], walk:["walk.png",10], attack:["attack1.png",16],
    hurt:["hurt.png",11], death:["death.png",6], cast:["cast2.png",21], attack2:["attack2.png",16],
    atk:11, spd:5.0, superDmg:38, superName:"Death Pact" },
  { id:"human-ranger", name:"Human Ranger", folder:"human-ranger", color:"#2e86c1", frameSize:128,
    idle:["idle.png",8], walk:["walk.png",8], attack:["attack1.png",20],
    hurt:["hurt.png",14], death:["death.png",24], jump:["jump.png",12], attack2:["attack2.png",28],
    projectile:"arrow_long.png",
    atk:10, spd:6.5, superDmg:30, superName:"Precision Volley" },
  { id:"human-mage", name:"Human Mage", folder:"human-mage", color:"#5b2c6f", frameSize:128,
    idle:["idle.png",18], walk:["walk.png",22], attack:["attack1.png",16],
    hurt:["hurt.png",16], death:["death.png",36], block:["block.png",27],
    cast:["cast.png",72], attack2:["attack2.png",47],
    projectile:"fireball.png",
    atk:10, spd:5.0, superDmg:44, superName:"Arcane Cataclysm" },
  { id:"water-priestess", name:"Water Priestess", folder:"water-priestess", color:"#2980b9", frameSize:128,
    idle:["idle.png",18], walk:["walk.png",22], attack:["attack1.png",16],
    hurt:["hurt.png",16], death:["death.png",36], block:["block.png",27],
    cast:["heal.png",27], attack2:["attack2.png",47],
    atk:9, spd:5.2, superDmg:38, superName:"Tidal Wave" },
  { id:"leaf-ranger", name:"Leaf Ranger", folder:"leaf-ranger", color:"#229954", frameSize:128,
    idle:["idle.png",27], walk:["run.png",22], attack:["attack1.png",22],
    hurt:["take_hit.png",14], death:["death.png",43], special:["special.png",38],
    attack2:["attack3.png",27], roll:["roll.png",18],
    projectile:"arrow_short.png",
    atk:10, spd:7.2, superDmg:28, superName:"Nature's Wrath" },
  { id:"wind-hashashin", name:"Wind Hashashin", folder:"wind-hashashin", color:"#1abc9c", frameSize:128,
    idle:["idle.png",18], walk:["run.png",18], attack:["attack1.png",18],
    hurt:["take_hit.png",14], death:["death.png",43], special:["special.png",68],
    attack2:["attack3.png",58], roll:["roll.png",14],
    atk:13, spd:7.4, superDmg:33, superName:"Gale Slash" },

  // ─── 80px frame heroes ─────────────────────────────────────────
  { id:"free-knight", name:"Free Knight", folder:"free-knight", color:"#aab7b8", frameSize:80,
    idle:["idle.png",15], walk:["walk.png",15], attack:["attack1.png",6],
    hurt:["hurt.png",2], death:["death.png",15], block:["block.png",18],
    jump:["jump.png",4], attack2:["attack2.png",9],
    atk:12, spd:5.6, superDmg:34, superName:"Noble Strike" },
  { id:"nightborne", name:"Nightborne", folder:"nightborne", color:"#2c3e50", frameSize:80,
    idle:["idle.png",9], walk:["walk.png",6], attack:["attack1.png",12],
    hurt:["hurt.png",5], death:["death.png",23], block:["block.png",3],
    cast:["cast.png",6], attack2:["attack2.png",6],
    atk:12, spd:5.8, superDmg:36, superName:"Void Collapse" },
  { id:"dwarf-ranger", name:"Dwarf Ranger", folder:"dwarf-ranger", color:"#a0522d", frameSize:80,
    idle:["idle.png",15], walk:["walk.png",15], attack:["attack1.png",6],
    hurt:["hurt.png",4], death:["death.png",15], roll:["roll.png",18], attack2:["attack2.png",9],
    projectile:"axe.png",
    atk:12, spd:5.2, superDmg:33, superName:"Dwarven Fury" },

  // ─── 64px frame heroes ─────────────────────────────────────────
  { id:"arcane-archer", name:"Arcane Archer", folder:"arcane-archer", color:"#1abc9c", frameSize:64,
    idle:["idle.png",6], walk:["walk.png",4], attack:["attack1.png",7],
    hurt:["hurt.png",5], death:["death.png",6], jump:["jump.png",2], attack2:["attack2.png",6],
    projectile:"arrow_long.png",
    atk:11, spd:6.6, superDmg:32, superName:"Arcane Volley" },
  { id:"shardsoul-slayer", name:"Shardsoul Slayer", folder:"shardsoul-slayer", color:"#c0392b", frameSize:64,
    idle:["idle.png",6], walk:["walk.png",6], attack:["attack1.png",6],
    hurt:["hurt.png",4], death:["death.png",6],
    atk:15, spd:6.0, superDmg:37, superName:"Soul Rend" },

  // ─── Unique frame size heroes ──────────────────────────────────
  { id:"elf-mage", name:"Elf Mage", folder:"Elf-mage", color:"#9b59b6", frameSize:190,
    idle:["Idle.png",7], walk:["Run.png",10], attack:["Attack1.png",10],
    hurt:["Hit.png",5], death:["Death.png",9], jump:["Jump.png",2], attack2:["Attack2.png",10],
    projectile:"fireball.png",
    atk:11, spd:5.6, superDmg:40, superName:"Arcane Storm" },
  { id:"evil-wizard", name:"Evil Wizard", folder:"evil-wizard", color:"#4a235a", frameSize:150,
    idle:["idle.png",8], walk:["walk.png",8], attack:["attack1.png",8],
    hurt:["hurt.png",4], death:["death.png",5], attack2:["attack2.png",8],
    projectile:"fireball.png",
    atk:12, spd:5.0, superDmg:42, superName:"Dark Cataclysm" },
  { id:"martial-hero", name:"Martial Hero", folder:"martial-hero", color:"#d4ac0d", frameSize:200,
    idle:["idle.png",8], walk:["walk.png",8], attack:["attack1.png",6],
    hurt:["hurt.png",4], death:["death.png",6], jump:["jump.png",2], attack2:["attack2.png",6],
    atk:13, spd:6.6, superDmg:34, superName:"Dragon Fist" },
  { id:"loreon-knight", name:"Loreon Knight", folder:"loreon-knight", color:"#f4d03f", frameSize:48,
    idle:["idle.png",3], walk:["walk.png",6], attack:["attack1.png",9],
    hurt:["hurt.png",3], death:["death.png",5], block:["block.png",5],
    jump:["jump.png",5], attack2:["attack2.png",9],
    atk:13, spd:5.8, superDmg:36, superName:"Loreon's Judgment" },
];
