// GRUDA Wars character roster — extracted from spriteMap.js
// All sprites live at /fighter2d/characters/<folder>/<file>.png

export interface GrudaCharDef {
  id: string;
  name: string;
  folder: string;
  color: string;
  idle: [string, number];
  walk: [string, number];
  attack: [string, number];
  hurt: [string, number];
  death: [string, number];
  attack2?: [string, number];
  block?: [string, number];
  jump?: [string, number];
  cast?: [string, number];
  special?: [string, number];
  projectile?: string; // from /fighter2d/projectiles/
  effectSrc?: string;  // from /fighter2d/effects/
  effectFrames?: number;
  // Stats
  atk: number;
  spd: number;
  superDmg: number;
  superName: string;
}

export const GRUDA_ROSTER: GrudaCharDef[] = [
  // === ORIGINAL 7 (100x100 GrudgeRPGAssets2d) ===
  { id:"knight", name:"Knight", folder:"Knight", color:"#e74c3c",
    idle:["Knight-Idle.png",6], walk:["Knight-Walk.png",8], attack:["Knight-Attack03.png",11],
    hurt:["Knight-Hurt.png",4], death:["Knight-Death.png",4], block:["Knight-Block.png",4],
    attack2:["Knight-Attack02.png",10],
    effectSrc:"Knight-Attack03_Effect.png", effectFrames:11,
    atk:13, spd:5.6, superDmg:35, superName:"Divine Judgment" },
  { id:"archer", name:"Archer", folder:"Archer", color:"#27ae60",
    idle:["Archer-Idle.png",6], walk:["Archer-Walk.png",8], attack:["Archer-Attack02.png",12],
    hurt:["Archer-Hurt.png",4], death:["Archer-Death.png",4],
    effectSrc:"Archer-Attack02_Effect.png", effectFrames:12, projectile:"Arrow.png",
    atk:9, spd:6.8, superDmg:30, superName:"Storm of Arrows" },
  { id:"wizard", name:"Wizard", folder:"Wizard", color:"#8e44ad",
    idle:["Wizard-Idle.png",6], walk:["Wizard-Walk.png",8], attack:["Wizard-Attack01.png",6],
    hurt:["Wizard-Hurt.png",4], death:["Wizard-DEATH.png",4],
    effectSrc:"Wizard-Attack01_Effect.png", effectFrames:10, projectile:"Wizard-Projectile.png",
    atk:10, spd:5.4, superDmg:40, superName:"Arcane Apocalypse" },
  { id:"orc", name:"Orc", folder:"Orc", color:"#2ecc71",
    idle:["Orc-Idle.png",6], walk:["Orc-Walk.png",8], attack:["Orc-Attack01.png",6],
    hurt:["Orc-Hurt.png",4], death:["Orc-Death.png",4],
    effectSrc:"Orc-attack01_Effect.png", effectFrames:6,
    atk:15, spd:5.0, superDmg:38, superName:"Waaagh! Smash" },
  { id:"skeleton", name:"Armored Skeleton", folder:"Armored-Skeleton", color:"#95a5a6",
    idle:["Armored Skeleton-Idle.png",6], walk:["Armored Skeleton-Walk.png",8],
    attack:["Armored Skeleton-Attack02.png",9], hurt:["Armored Skeleton-Hurt.png",4],
    death:["Armored Skeleton-Death.png",4],
    effectSrc:"Armored Skeleton-Attack02_Effect.png", effectFrames:9,
    atk:11, spd:5.8, superDmg:32, superName:"Soul Harvest" },
  { id:"swordsman", name:"Swordsman", folder:"Swordsman", color:"#e67e22",
    idle:["Swordsman-Idle.png",6], walk:["Swordsman-Walk.png",8], attack:["Swordsman-Attack01.png",7],
    hurt:["Swordsman-Hurt.png",5], death:["Swordsman-Death.png",4],
    effectSrc:"Swordsman-Attack01_Effect.png", effectFrames:7,
    atk:12, spd:6.4, superDmg:33, superName:"Thousand Cuts" },
  { id:"priest", name:"Priest", folder:"Priest", color:"#f1c40f",
    idle:["Priest-Idle.png",6], walk:["Priest-Walk.png",8], attack:["Priest-Attack.png",9],
    hurt:["Priest-Hurt.png",4], death:["Priest-Death.png",4], cast:["Priest-Heal.png",6],
    effectSrc:"Priest-Attack_effect.png", effectFrames:5,
    atk:9, spd:5.2, superDmg:36, superName:"Holy Smite" },

  // === GRUDA WARS HEROES ===
  { id:"dark-knight", name:"Dark Knight", folder:"dark-knight", color:"#2c3e50",
    idle:["idle.png",4], walk:["walk.png",6], attack:["attack1.png",8],
    hurt:["hurt.png",3], death:["death.png",4], jump:["jump.png",6],
    attack2:["attack2.png",11],
    effectSrc:"slash_arc.png", effectFrames:6,
    atk:14, spd:5.8, superDmg:36, superName:"Shadow Cleave" },
  { id:"fire-knight", name:"Fire Knight", folder:"fire-knight", color:"#e74c3c",
    idle:["idle.png",7], walk:["run.png",8], attack:["attack1.png",6],
    hurt:["hurt.png",3], death:["death.png",6], block:["block.png",4],
    jump:["jump.png",8], attack2:["attack2.png",6], special:["special.png",12],
    atk:14, spd:6.2, superDmg:38, superName:"Inferno Blade" },
  { id:"elf-ranger", name:"Elf Ranger", folder:"elf-ranger", color:"#27ae60",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",9],
    hurt:["hurt.png",4], death:["death.png",4], attack2:["attack2.png",12],
    projectile:"arrow_long.png",
    atk:10, spd:7.0, superDmg:28, superName:"Elven Barrage" },
  { id:"elf-mage", name:"Elf Mage", folder:"Elf-mage", color:"#9b59b6",
    idle:["Idle.png",6], walk:["Run.png",8], attack:["Attack1.png",8],
    hurt:["Hit.png",4], death:["Death.png",4], jump:["Jump.png",3],
    attack2:["Attack2.png",8],
    projectile:"fireball.png",
    atk:11, spd:5.6, superDmg:40, superName:"Arcane Storm" },
  { id:"barbarian-warrior", name:"Barbarian", folder:"barbarian-warrior", color:"#d35400",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",6],
    hurt:["hurt.png",4], death:["death.png",4], attack2:["attack2.png",6],
    atk:16, spd:4.8, superDmg:42, superName:"Berserker Fury" },
  { id:"barbarian-ranger", name:"Barbarian Ranger", folder:"barbarian-ranger", color:"#c0392b",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",9],
    hurt:["hurt.png",4], death:["death.png",4],
    projectile:"axe.png",
    atk:12, spd:5.6, superDmg:34, superName:"Axe Storm" },
  { id:"necromancer", name:"Necromancer", folder:"necromancer", color:"#6c3483",
    idle:["idle.png",8], walk:["walk.png",8], attack:["attack1.png",13],
    hurt:["hurt.png",9], death:["death.png",5], cast:["cast2.png",17],
    atk:11, spd:5.0, superDmg:38, superName:"Death Pact" },
  { id:"pirate-captain", name:"Pirate Captain", folder:"pirate-captain", color:"#784212",
    idle:["Idle.png",10], walk:["Walk.png",8], attack:["Attack1.png",6],
    hurt:["Hurt.png",3], death:["Death.png",7], special:["Special.png",10],
    attack2:["Attack2.png",4],
    projectile:"bullet.png",
    atk:13, spd:5.8, superDmg:35, superName:"Cannon Barrage" },
  { id:"gunslinger", name:"Gunslinger", folder:"gunslinger", color:"#7f8c8d",
    idle:["idle.png",4], walk:["walk.png",6], attack:["attack.png",6],
    hurt:["hurt.png",2], death:["death.png",6],
    projectile:"bullet.png",
    atk:11, spd:6.6, superDmg:30, superName:"Dead Eye" },
  { id:"shadow-warrior", name:"Shadow Warrior", folder:"shadow-warrior", color:"#1a1a2e",
    idle:["idle.png",4], walk:["walk.png",6], attack:["attack1.png",12],
    hurt:["hurt.png",3], death:["death.png",4], jump:["jump.png",5],
    attack2:["attack2.png",7],
    atk:13, spd:6.4, superDmg:34, superName:"Shadow Dance" },
  { id:"fire-wizard", name:"Fire Wizard", folder:"fire-wizard", color:"#e74c3c",
    idle:["idle.png",7], walk:["walk.png",6], attack:["attack1.png",4],
    hurt:["hurt.png",3], death:["death.png",6], jump:["jump.png",9],
    cast:["fireball.png",8],
    projectile:"fireball.png",
    atk:10, spd:5.4, superDmg:42, superName:"Meteor Rain" },
  { id:"lightning-mage", name:"Lightning Mage", folder:"lightning-mage", color:"#3498db",
    idle:["idle.png",7], walk:["walk.png",7], attack:["attack1.png",10],
    hurt:["hurt.png",3], death:["death.png",5], jump:["jump.png",8],
    cast:["light_ball.png",7],
    effectSrc:"lightning-bolt.png", effectFrames:6,
    atk:11, spd:5.6, superDmg:40, superName:"Thunder God" },
  { id:"dwarf-ranger", name:"Dwarf Ranger", folder:"dwarf-ranger", color:"#a0522d",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",9],
    hurt:["hurt.png",4], death:["death.png",4],
    projectile:"axe.png",
    atk:12, spd:5.2, superDmg:33, superName:"Dwarven Fury" },
  { id:"human-ranger", name:"Human Ranger", folder:"human-ranger", color:"#2e86c1",
    idle:["idle.png",8], walk:["walk.png",8], attack:["attack1.png",14],
    hurt:["hurt.png",14], death:["death.png",24], jump:["jump.png",12],
    projectile:"arrow_long.png",
    atk:10, spd:6.5, superDmg:30, superName:"Precision Volley" },
  { id:"human-mage", name:"Human Mage", folder:"human-mage", color:"#5b2c6f",
    idle:["idle.png",8], walk:["walk.png",10], attack:["attack1.png",7],
    hurt:["hurt.png",7], death:["death.png",16], block:["block.png",12],
    cast:["cast.png",32],
    projectile:"fireball.png",
    atk:10, spd:5.0, superDmg:44, superName:"Arcane Cataclysm" },
  { id:"knight-templar", name:"Knight Templar", folder:"knight-templar", color:"#f39c12",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack3.png",11],
    hurt:["hurt.png",4], death:["death.png",4], block:["block.png",4],
    cast:["cast.png",11],
    atk:14, spd:5.4, superDmg:37, superName:"Holy Crusade" },
  { id:"crossbowman", name:"Crossbowman", folder:"crossbowman", color:"#566573",
    idle:["Idle.png",6], walk:["Walk.png",8], attack:["Attack_1.png",6],
    hurt:["Hurt.png",3], death:["Dead.png",6], jump:["Jump.png",5],
    projectile:"ballista_bolt.png",
    atk:12, spd:5.8, superDmg:32, superName:"Bolt Barrage" },
  { id:"werebear", name:"Werebear", folder:"werebear", color:"#6e2c00",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",9],
    hurt:["hurt.png",4], death:["death.png",4], attack2:["attack3.png",9],
    atk:16, spd:4.6, superDmg:42, superName:"Bear Maul" },
  { id:"werewolf", name:"Werewolf", folder:"werewolf", color:"#4a235a",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",9],
    hurt:["hurt.png",4], death:["death.png",4], attack2:["attack2.png",13],
    atk:14, spd:6.8, superDmg:35, superName:"Lunar Frenzy" },
  { id:"arcane-archer", name:"Arcane Archer", folder:"arcane-archer", color:"#1abc9c",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",9],
    hurt:["hurt.png",4], death:["death.png",4], jump:["jump.png",6],
    projectile:"arrow_long.png",
    atk:11, spd:6.6, superDmg:32, superName:"Arcane Volley" },
  { id:"leaf-ranger", name:"Leaf Ranger", folder:"leaf-ranger", color:"#229954",
    idle:["idle.png",6], walk:["run.png",8], attack:["attack1.png",7],
    hurt:["take_hit.png",3], death:["death.png",4], special:["special.png",8],
    attack2:["attack3.png",7],
    projectile:"arrow_short.png",
    atk:10, spd:7.2, superDmg:28, superName:"Nature's Wrath" },
  { id:"martial-hero", name:"Martial Hero", folder:"martial-hero", color:"#d4ac0d",
    idle:["idle.png",8], walk:["walk.png",8], attack:["attack1.png",6],
    hurt:["hurt.png",3], death:["death.png",6], jump:["jump.png",3],
    attack2:["attack2.png",4],
    atk:13, spd:6.6, superDmg:34, superName:"Dragon Fist" },
  { id:"free-knight", name:"Free Knight", folder:"free-knight", color:"#aab7b8",
    idle:["idle.png",10], walk:["walk.png",10], attack:["attack1.png",4],
    hurt:["hurt.png",1], death:["death.png",10], block:["block.png",12],
    jump:["jump.png",3], attack2:["attack2.png",6],
    atk:12, spd:5.6, superDmg:34, superName:"Noble Strike" },
  { id:"nightborne", name:"Nightborne", folder:"nightborne", color:"#2c3e50",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",8],
    hurt:["hurt.png",4], death:["death.png",4], block:["block.png",4],
    cast:["cast.png",8], attack2:["attack2.png",8],
    atk:12, spd:5.8, superDmg:36, superName:"Void Collapse" },
  { id:"wind-hashashin", name:"Wind Hashashin", folder:"wind-hashashin", color:"#1abc9c",
    idle:["idle.png",6], walk:["run.png",8], attack:["attack1.png",6],
    hurt:["take_hit.png",3], death:["death.png",4], special:["special.png",8],
    attack2:["attack3.png",8],
    atk:13, spd:7.4, superDmg:33, superName:"Gale Slash" },
  { id:"water-priestess", name:"Water Priestess", folder:"water-priestess", color:"#2980b9",
    idle:["idle.png",8], walk:["walk.png",10], attack:["attack1.png",7],
    hurt:["hurt.png",7], death:["death.png",16], block:["block.png",12],
    cast:["heal.png",12],
    atk:9, spd:5.2, superDmg:38, superName:"Tidal Wave" },
  { id:"shardsoul-slayer", name:"Shardsoul Slayer", folder:"shardsoul-slayer", color:"#c0392b",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",8],
    hurt:["hurt.png",4], death:["death.png",4],
    atk:15, spd:6.0, superDmg:37, superName:"Soul Rend" },
  { id:"loreon-knight", name:"Loreon Knight", folder:"loreon-knight", color:"#f4d03f",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",8],
    hurt:["hurt.png",4], death:["death.png",4], block:["block.png",4],
    jump:["jump.png",6], attack2:["attack2.png",8],
    atk:13, spd:5.8, superDmg:36, superName:"Loreon's Judgment" },
  { id:"elite-orc", name:"Elite Orc", folder:"elite-orc", color:"#196f3d",
    idle:["idle.png",6], walk:["walk.png",8], attack:["attack1.png",7],
    hurt:["hurt.png",4], death:["death.png",4], attack2:["attack2.png",11],
    atk:15, spd:5.2, superDmg:40, superName:"Orc Warlord" },
  { id:"evil-wizard", name:"Evil Wizard", folder:"evil-wizard", color:"#4a235a",
    idle:["idle.png",8], walk:["walk.png",8], attack:["attack1.png",8],
    hurt:["hurt.png",4], death:["death.png",5],
    projectile:"fireball.png",
    atk:12, spd:5.0, superDmg:42, superName:"Dark Cataclysm" },
];
